baseURL: https://blog.qingbo.tech/
footnoteReturnLinkContents: ↩
params:
  AuthorName: 张清波
  GitHubUser: ripple0328
  SidebarRecentLimit: 5
permalinks:
  posts: /:year/:month/:title/
title: Qingbo
theme: "base16"
pygmentsuseclasses: true
