baseURL: https://blogd.qinggbo.tech/
footnoteReturnLinkContents: ↩
params:
  AuthorName: 张清波
  GitHubUser: ripple0328
  SidebarRecentLimit: 5
  Subtitle: my blog
permalinks:
  posts: /:year/:month/:title/
title: Qingbo
theme: "base16"
pygmentsuseclasses: true
