baseURL: https://blog.qingbo.tech/
footnoteReturnLinkContents: ↩
params:
  AuthorName: Ripple
  GitHubUser: ripple0328
  SidebarRecentLimit: 5
permalinks:
  posts: /:year/:month/:title/
title: Titalium
theme: "base16"
pygmentsuseclasses: true
